#!/usr/bin/env python
#
##############################################################################
#
# MODULE:       model
#
# AUTHOR(S):    rsb
#               
# PURPOSE:      Script generated by wxGUI Graphical Modeler.
#
# DATE:         Fri Apr 11 14:38:34 2014
#
##############################################################################

#%module
#% description: Script generated by wxGUI Graphical Modeler.
#%end

import sys
import os
import atexit

from grass.script import parser, run_command

def cleanup():
    pass

def main():
    run_command("g.mapset",
                mapset = "elevation")

    run_command("g.region",
                flags = 'p',
                rast = "N14E074UK@elevation")

    run_command("v.hull",
                overwrite = True,
                input = "wlr_mar14@gps",
                layer = "-1",
                output = "chull_wlr_mar14")

    run_command("v.hull",
                overwrite = True,
                input = "tbrg_mar14@gps",
                layer = "-1",
                output = "chull_tbrg_mar14")

    run_command("v.patch",
                overwrite = True,
                input = "chull_wlr_mar14,chull_tbrg_mar14@gps",
                output = "wlr_tbrg_patch")

    run_command("v.buffer",
                overwrite = True,
                input = "wlr_tbrg_patch",
                layer = "-1",
                type = "area",
                output = "wlr_tbrg_patch_50kbuffer",
                distance = 50000,
                angle = 0,
                scale = 1.0,
                tolerance = 0.01)

    run_command("v.to.rast",
                overwrite = True,
                input = "wlr_tbrg_patch_50kbuffer",
                layer = "1",
                type = "area",
                output = "MASK@elevation",
                use = "val",
                value = 1,
                rows = 4096)

    run_command("g.region",
                rast = "MASK@elevation")

run_command("g.remove",
                flags = 'f',
                vect = "chull_wlr_mar14,chull_tbrg_mar14,wlr_tbrg_patch,wlr_tbrg_patch_5kbuffer")


    return 0

if __name__ == "__main__":
    options, flags = parser()
    atexit.register(cleanup)
    sys.exit(main())
